apiVersion: v1
kind: Pod
metadata:
  name: nginx-pod-2
  labels:
    app: nginx
spec:
  hostname: pod-b # 생략 O
  subdomain: nginx-headless # 생략 X(필수)
  containers:
  - name: nginx
    image: nginx
    ports:
    - containerPort: 80
