apiVersion: v1
kind: Pod
metadata:
  name: nginx-pod-3
  namespace: quota-demo
spec:
  containers:
  - name: nginx
    image: nginx
    resources:
      requests:
        cpu: "200m"
        memory: "256Mi"
      limits:
        cpu: "500m"
        memory: "512Mi"

