apiVersion: v1
kind: Service
metadata:
  name: nginx-nodeport-svc
spec:
  type: NodePort
  selector:
    app: my-nginx
  ports:
  - port: 80        # service port(cluster)
    targetPort: 80  # container port
    nodePort: 30080 # outside accessable port
