apiVersion: v1
kind: Pod
metadata:
  name: pvc-pod
spec:
  volumes:
  - name: storage
    persistentVolumeClaim:
      claimName: demo-pvc

  containers:
  - name: my-nginx
    image: nginx
    volumeMounts:
    - name: storage
      mountPath: /data
