apiVersion: v1
kind: Pod
metadata:
  name: test-pod
spec:
  containers:
  - name: my-nginx
    image: nginx
    volumeMounts:
    - mountPath: /data
      name: test-vol

  volumes:
  - name: test-vol
    persistentVolumeClaim:
      claimName: test-pvc
