apiVersion: v1
kind: Pod
metadata:
  name: longhorn-test
spec:
  containers:
  - name: my-nginx
    image: nginx
    volumeMounts:
    - mountPath: /data
      name: longhorn-vol

  volumes:
  - name: longhorn-vol
    persistentVolumeClaim:
      claimName: longhorn-pvc
