# kubectl create configmap cm-dev --from-literal=app.properties="APP_MODE=production"
# kubectl create secret generic sec-dev --from-literal=credentials.txt="user=admin\npassword=1234"
---
apiVersion: v1
kind: Pod
metadata:
  name: cm-sec-pod
spec:
  containers:
  - name: app
    image: kubetm/init
    volumeMounts:
    - name: cm-volume
      mountPath: /etc/config
    - name: sec-volume
      mountPath: /etc/secret

  volumes:
  - name: cm-volume
    configMap:
      name: cm-dev
  - name: sec-volume
    secret:
      secretName: sec-dev
